# Generated by Django 4.1.7 on 2023-03-21 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(unique=True)),
                ('reserved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('deruration', models.TimeField()),
                ('sessionUrl', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ended_at', models.DateTimeField()),
                ('available_dates', models.ManyToManyField(to='roomsession.sessiondate')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('tags', models.ManyToManyField(blank=True, to='tags.tags')),
            ],
        ),
    ]
