# Generated by Django 4.1.7 on 2023-03-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsession', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsession',
            name='user_bio',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
