# Generated by Django 4.1.7 on 2023-03-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsession', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondate',
            name='datetime',
            field=models.DateField(unique=True),
        ),
    ]
