# Generated by Django 4.1.7 on 2023-03-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsession', '0003_remove_roomsession_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
