# Generated by Django 4.1.7 on 2023-03-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsession', '0004_roomsession_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsession',
            name='read_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
