# Generated by Django 4.1.7 on 2023-04-04 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roomsession', '0005_roomsession_read_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomsession',
            name='read_time',
        ),
        migrations.AddField(
            model_name='sessiondate',
            name='reserver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reserve', to=settings.AUTH_USER_MODEL),
        ),
    ]
