# Generated by Django 4.1.7 on 2023-04-04 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roomsession', '0006_remove_roomsession_read_time_sessiondate_reserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsession',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_session', to=settings.AUTH_USER_MODEL),
        ),
    ]
