# Generated by Django 4.1.7 on 2023-04-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsession', '0007_alter_roomsession_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsession',
            name='read_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
