# Generated by Django 4.1.7 on 2023-04-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsession', '0007_alter_roomsession_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomsession',
            name='deruration',
        ),
        migrations.AddField(
            model_name='sessiondate',
            name='deruration',
            field=models.TimeField(default='06:00:00'),
            preserve_default=False,
        ),
    ]
