# Generated by Django 4.1.7 on 2023-04-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsession', '0008_remove_roomsession_deruration_sessiondate_deruration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondate',
            name='deruration',
            field=models.TimeField(null=True),
        ),
    ]
