# Generated by Django 4.1.7 on 2023-04-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsession', '0008_alter_subscription_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
