# Generated by Django 4.1.7 on 2023-04-06 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomsession', '0008_roomsession_read_time'),
        ('roomsession', '0011_alter_roomsession_sessionurl'),
    ]

    operations = [
    ]
