# Generated by Django 4.1.7 on 2023-04-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsession', '0011_gmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Gmail',
        ),
    ]
