# Generated by Django 4.1.7 on 2023-04-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsession', '0012_merge_20230406_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomsession',
            name='read_time',
        ),
        migrations.AlterField(
            model_name='roomsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
