# Generated by Django 4.1.7 on 2023-04-06 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomsession', '0012_merge_20230406_0739'),
        ('roomsession', '0013_remove_roomsession_read_time_and_more'),
    ]

    operations = [
    ]
