# Generated by Django 4.1.7 on 2023-04-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsession', '0014_merge_20230407_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiondate',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=10),
            preserve_default=False,
        ),
    ]
