# Generated by Django 4.1.7 on 2023-04-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomsession', '0014_merge_20230406_2212'),
        ('roomsession', '0014_merge_20230407_1157'),
    ]

    operations = [
    ]
