# Generated by Django 4.1.7 on 2023-03-21 15:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, max_length=150, null=True)),
                ('usertype', models.CharField(choices=[('mentor', 'Mentor'), ('student', 'Student')], default='student', max_length=10)),
                ('user_profile', models.ImageField(blank=True, upload_to='images/')),
                ('phone', models.CharField(max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='phone must be an egyptian phone number...', regex='^01[1|0|2|5][0-9]{8}$')], verbose_name='phone')),
                ('date_birth', models.DateField(null=True)),
                ('facebook_link', models.URLField(null=True)),
                ('github_link', models.URLField(null=True)),
                ('instgram_link', models.URLField(null=True)),
                ('joinDate', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.user')),
                ('favourite_bins', models.ManyToManyField(blank=True, to='tags.tags')),
            ],
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.user')),
                ('specializations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_specialization', to='tags.specialization')),
                ('tools', models.ManyToManyField(blank=True, related_name='mentor_tools', to='tags.tools')),
            ],
            bases=('accounts.user',),
        ),
    ]
