# Generated by Django 4.1.7 on 2023-03-27 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
