# Generated by Django 4.1.7 on 2023-04-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_mentor_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile',
            field=models.ImageField(blank=True, upload_to='images/accounts'),
        ),
    ]
