# Generated by Django 4.1.7 on 2023-04-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_tags_caption'),
        ('accounts', '0005_alter_user_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite_bins',
            field=models.ManyToManyField(blank=True, to='tags.tags'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='mentor_tools', to='tags.tools'),
        ),
    ]
