# Generated by Django 4.1.7 on 2023-04-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='caption',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
